apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: strapi
        image: gcr.io/expanded-rider-445003-j0/strapi:latest
        ports:
        - containerPort: 1337
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "1337"